"use client";

import { useActionState, useState } from "react";
import { Check, Mail, Send, X } from "lucide-react";
import { sendManualEmail } from "@/app/messages/actions";

export type EmailLogRow = { id: string; notification_type: string; recipient_name: string | null; recipient_email: string; subject: string; status: string; error_message: string | null; created_at: string };
const initial = { success: false, message: "" };
const types: Record<string, string> = { task_assignment: "משימה חדשה", daily_digest: "דיוור יומי", expiry_alert: "התראת תפוגה", manual: "ידני" };
const recipients = [{ key: "eden", name: "עדן", email: "eden@caeli.pro" }, { key: "sergey", name: "סרגיי", email: "sergey@caeli.pro" }, { key: "quality_manager", name: "עמית", email: "amit.a@caeli.pro" }] as const;

export function MessagesCenter({ rows }: { rows: EmailLogRow[] }) {
  const [open, setOpen] = useState(false);
  const [recipient, setRecipient] = useState("eden");
  const [state, action, pending] = useActionState(sendManualEmail, initial);
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div><h1 className="text-3xl font-extrabold">הודעות</h1><p className="mt-2 text-slate-500">מעקב אחר מיילים אוטומטיים ושליחה ידנית</p></div><button type="button" onClick={() => setOpen(true)} className="h-11 rounded-xl bg-slate-950 px-5 font-bold text-white"><Send className="ml-2 inline h-4 w-4" />שליחת מייל</button></div>
    <div className="overflow-hidden rounded-2xl border bg-white"><h2 className="border-b p-5 text-xl font-extrabold"><Mail className="ml-2 inline" />היסטוריית שליחות</h2><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-right text-sm"><thead className="bg-slate-50"><tr>{["מועד", "סוג", "נמען", "נושא", "מצב", "פרטים"].map((heading) => <th key={heading} className="p-4">{heading}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t"><td className="p-4">{new Intl.DateTimeFormat("he-IL", { dateStyle: "short", timeStyle: "short", timeZone: "Asia/Jerusalem" }).format(new Date(row.created_at))}</td><td className="p-4 font-bold">{types[row.notification_type] ?? row.notification_type}</td><td className="p-4">{row.recipient_name || row.recipient_email}</td><td className="p-4">{row.subject}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${row.status === "sent" ? "bg-emerald-100 text-emerald-700" : row.status === "sending" ? "bg-amber-100 text-amber-700" : "bg-red-100 text-red-700"}`}>{row.status === "sent" ? "נשלח" : row.status === "sending" ? "בשליחה" : "נכשל"}</span></td><td className="p-4 text-xs text-red-600">{row.error_message || "—"}</td></tr>)}</tbody></table></div></div>
    {open ? <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><button type="button" aria-label="סגירה" className="absolute inset-0 bg-slate-950/45" onClick={() => setOpen(false)} /><form action={action} className="relative z-10 w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-2xl font-extrabold">שליחת מייל ידנית</h2><p className="mt-1 text-sm text-slate-500">בחר נמען ממחלקת האיכות</p></div><button type="button" aria-label="סגירה" onClick={() => setOpen(false)}><X /></button></div><div className="mt-5 grid gap-4"><div className="grid grid-cols-3 gap-2">{recipients.map((item) => <label key={item.key} className={`relative cursor-pointer rounded-xl border p-3 text-center transition ${recipient === item.key ? "border-slate-950 bg-slate-950 text-white" : "bg-white hover:bg-slate-50"}`}><input type="radio" name="recipient_key" value={item.key} checked={recipient === item.key} onChange={() => setRecipient(item.key)} className="sr-only" /><span className="block font-extrabold">{item.name}</span><span className={`mt-1 block truncate text-[10px] ${recipient === item.key ? "text-slate-300" : "text-slate-500"}`}>{item.email}</span>{recipient === item.key ? <Check className="absolute left-2 top-2 h-4 w-4" /> : null}</label>)}</div><label className="text-sm font-bold">נושא<input required name="subject" maxLength={200} className="mt-1 h-11 w-full rounded-lg border px-3" /></label><label className="text-sm font-bold">תוכן<textarea required name="body" rows={7} maxLength={10000} className="mt-1 w-full rounded-lg border p-3" /></label>{state.message ? <p role="status" className={`rounded-lg p-3 text-sm font-bold ${state.success ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{state.message}</p> : null}<button disabled={pending} className="h-11 rounded-lg bg-slate-950 font-bold text-white disabled:opacity-50">{pending ? "שולח..." : `שליחה אל ${recipients.find((item) => item.key === recipient)?.name}`}</button></div></form></div> : null}
  </div>;
}
